import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

final localeProvider = StateProvider<String>((ref) {
  return Hive.box('settings').get('language', defaultValue: 'en');
});

final l10nProvider = Provider((ref) {
  final locale = ref.watch(localeProvider);
  return AppLocalization(locale);
});

class AppLocalization {
  final String locale;
  AppLocalization(this.locale);

  static const _en = {
    'namaste': 'Namaste,',
    'teacher': 'Teacher!',
    'daily_overview': 'Here is your daily teaching overview.',
    'scan_digitize': 'Scan & Digitize',
    'scan_desc': 'Instantly capture handwritten notes, assignments...',
    'start_scanning': 'Start Scanning',
    'check_topic': 'Check Topic',
    'topic_desc': 'Review today\'s curriculum',
    'class_schedule': 'Class Schedule',
    'schedule_desc': 'View your weekly timetable',
    'recent_activity': 'Recent Activity',
    'no_recent_scans': 'No recent scans yet.',
    'home': 'Home',
    'library': 'Library',
    'scan': 'Scan',
    'history': 'History',
    'profile': 'Profile',
    'logout': 'Logout',
    'logout_confirm': 'Are you sure you want to logout?',
    'cancel': 'Cancel',
    'settings': 'Settings',
    'language': 'Language',
    'sync_data': 'Sync Data',
    'upload_confirm': 'Do you want to start uploading your documents to the server?',
    'uploading': 'Uploading documents...',
    'upload_success_title': 'Upload Successful?',
    'upload_success_desc': 'Please confirm if all your documents and images were uploaded successfully. \n\nWarning: Confirming will permanently delete local history to start a fresh 30-day cycle.',
    'confirm_delete': 'Confirm & Delete Local',
    'no_not_yet': 'No, Not Yet',
    'scan_center': 'Scan Center',
    'digitize_textbook': 'Digitize Textbook',
    'handwritten_notes': 'Handwritten Notes',
    'quick_id_scan': 'Quick ID Scan',
    'qr_redirect': 'QR Code / Redirect',
    'scanner_tips': 'Scanner Tips',
    'tip1': '• Ensure good, even lighting. Natural daylight works best.',
    'tip2': '• Keep the document flat and parallel to the camera.',
    'tip3': '• Use a contrasting background like a dark table.',
    'tip4': '• Tap the screen to focus if the text appears blurry.',
    'morning_attendance': 'Morning Attendance',
    'total': 'TOTAL',
    'present': 'PRESENT',
    'absent': 'ABSENT',
    'late': 'LATE',
    'search_student': 'Search student name...',
    'submit_attendance': 'Submit Attendance',
    'attendance_success': 'Attendance Submitted Successfully!',
    'roll_no': 'Roll No.',
    'teaching_resources': 'Teaching Resources',
    'my_subjects': 'My Subjects',
    'syllabus_guides': 'Syllabus & Guides',
    'class_8_science': 'Class 8 Science',
    'class_7_math': 'Class 7 Mathematics',
    'items': 'Items',
    'ncert_guide': 'NCERT Science Guide 2024',
    'math_lesson': 'Math Lesson Plans Term 1',
  };

  static const _hi = {
    'namaste': 'नमस्ते,',
    'teacher': 'शिक्षक!',
    'daily_overview': 'यहाँ आपकी दैनिक शिक्षण समीक्षा है।',
    'scan_digitize': 'स्कैन और डिजिटाइज़',
    'scan_desc': 'हाथ से लिखे नोट्स, असाइनमेंट को तुरंत कैप्चर करें...',
    'start_scanning': 'स्कैन शुरू करें',
    'check_topic': 'विषय जांचें',
    'topic_desc': 'आज के पाठ्यक्रम की समीक्षा करें',
    'class_schedule': 'कक्षा अनुसूची',
    'schedule_desc': 'अपनी साप्ताहिक समय सारिणी देखें',
    'recent_activity': 'हाल की गतिविधि',
    'no_recent_scans': 'अभी तक कोई हालिया स्कैन नहीं है।',
    'home': 'होम',
    'library': 'लाइब्रेरी',
    'scan': 'स्कैन',
    'history': 'इतिहास',
    'profile': 'प्रोफ़ाइल',
    'logout': 'लॉगआउट',
    'logout_confirm': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
    'cancel': 'रद्द करें',
    'settings': 'सेटिंग्स',
    'language': 'भाषा',
    'sync_data': 'डेटा सिंक करें',
    'upload_confirm': 'क्या आप अपने दस्तावेज़ों को सर्वर पर अपलोड करना शुरू करना चाहते हैं?',
    'uploading': 'दस्तावेज़ अपलोड हो रहे हैं...',
    'upload_success_title': 'अपलोड सफल?',
    'upload_success_desc': 'कृपया पुष्टि करें कि आपके सभी दस्तावेज़ और चित्र सफलतापूर्वक अपलोड किए गए थे। \n\nचेतावनी: पुष्टि करने से नया 30-दिन का चक्र शुरू करने के लिए स्थानीय इतिहास स्थायी रूप से हटा दिया जाएगा।',
    'confirm_delete': 'पुष्टि करें और स्थानीय हटाएं',
    'no_not_yet': 'नहीं, अभी नहीं',
    'scan_center': 'स्कैन सेंटर',
    'digitize_textbook': 'पाठ्यपुस्तक डिजिटाइज़ करें',
    'handwritten_notes': 'हाथ से लिखे नोट्स',
    'quick_id_scan': 'त्वरित आईडी स्कैन',
    'qr_redirect': 'क्यूआर कोड / रीडायरेक्ट',
    'scanner_tips': 'स्कैनर टिप्स',
    'tip1': '• अच्छी, समान रोशनी सुनिश्चित करें। प्राकृतिक दिन की रोशनी सबसे अच्छी काम करती है।',
    'tip2': '• दस्तावेज़ को समतल और कैमरे के समानांतर रखें।',
    'tip3': '• डार्क टेबल जैसा विपरीत बैकग्राउंड उपयोग करें।',
    'tip4': '• यदि टेक्स्ट धुंधला दिखाई दे तो फोकस करने के लिए स्क्रीन पर टैप करें।',
    'morning_attendance': 'सुबह की उपस्थिति',
    'total': 'कुल',
    'present': 'उपस्थित',
    'absent': 'अनुपस्थित',
    'late': 'देर से',
    'search_student': 'छात्र का नाम खोजें...',
    'submit_attendance': 'उपस्थिति जमा करें',
    'attendance_success': 'उपस्थिति सफलतापूर्वक जमा की गई!',
    'roll_no': 'रोल नंबर',
    'teaching_resources': 'शिक्षण संसाधन',
    'my_subjects': 'मेरे विषय',
    'syllabus_guides': 'पाठ्यक्रम और मार्गदर्शिकाएँ',
    'class_8_science': 'कक्षा 8 विज्ञान',
    'class_7_math': 'कक्षा 7 गणित',
    'items': 'आइटम',
    'ncert_guide': 'एनसीईआरटी विज्ञान मार्गदर्शिका 2024',
    'math_lesson': 'गणित पाठ योजना टर्म 1',
  };

  static const _hinglish = {
    'namaste': 'Namaste,',
    'teacher': 'Teacher!',
    'daily_overview': 'Ye aapka daily teaching overview hai.',
    'scan_digitize': 'Scan & Digitize',
    'scan_desc': 'Handwritten notes, assignments ko turant capture karein...',
    'start_scanning': 'Scanning Start Karein',
    'check_topic': 'Topic Check Karein',
    'topic_desc': 'Aaj ka syllabus review karein',
    'class_schedule': 'Class Schedule',
    'schedule_desc': 'Apna weekly timetable dekhein',
    'recent_activity': 'Recent Activity',
    'no_recent_scans': 'Abhi tak koi scan nahi hai.',
    'home': 'Home',
    'library': 'Library',
    'scan': 'Scan',
    'history': 'History',
    'profile': 'Profile',
    'logout': 'Logout',
    'logout_confirm': 'Kya aap sach mein logout karna chahte hain?',
    'cancel': 'Cancel',
    'settings': 'Settings',
    'language': 'Language',
    'sync_data': 'Sync Data',
    'upload_confirm': 'Kya aap apne documents server par upload karna chahte hain?',
    'uploading': 'Documents upload ho rahe hain...',
    'upload_success_title': 'Upload Success?',
    'upload_success_desc': 'Confirm karein agar sab documents upload ho gaye hain. \n\nWarning: Isse local history delete ho jayegi.',
    'confirm_delete': 'Confirm & Local Delete',
    'no_not_yet': 'Nahi, abhi nahi',
    'scan_center': 'Scan Center',
    'digitize_textbook': 'Textbook Digitize Karein',
    'handwritten_notes': 'Handwritten Notes',
    'quick_id_scan': 'Quick ID Scan',
    'qr_redirect': 'QR Code / Redirect',
    'scanner_tips': 'Scanner Tips',
    'tip1': '• Roshni (light) acchi honi chahiye.',
    'tip2': '• Document ko seedha rakhein.',
    'tip3': '• Dark background use karein.',
    'tip4': '• Screen par tap karein focus ke liye.',
    'morning_attendance': 'Morning Attendance',
    'total': 'TOTAL',
    'present': 'PRESENT',
    'absent': 'ABSENT',
    'late': 'LATE',
    'search_student': 'Student name search karein...',
    'submit_attendance': 'Attendance Submit Karein',
    'attendance_success': 'Attendance successfully submit ho gayi!',
    'roll_no': 'Roll No.',
    'teaching_resources': 'Teaching Resources',
    'my_subjects': 'Mere Subjects',
    'syllabus_guides': 'Syllabus & Guides',
    'class_8_science': 'Class 8 Science',
    'class_7_math': 'Class 7 Mathematics',
    'items': 'Items',
    'ncert_guide': 'NCERT Science Guide 2024',
    'math_lesson': 'Math Lesson Plans Term 1',
  };

  String tr(String key) {
    if (locale == 'hi') return _hi[key] ?? _en[key] ?? key;
    if (locale == 'hinglish') return _hinglish[key] ?? _en[key] ?? key;
    return _en[key] ?? key;
  }
}
